baseurl: "http://KeenS.github.io"
languageCode: "en-us"
title: κeenのHappy Hacκing Blog
permalinks:
  post: /blog/:year/:month/:day/:filename
canonifyurls: true

MetaDataFormat: yaml

menu:
  main:
    - name: Blog
      url: /post
    - name: Slide
      url: /slide

params:
  categories: true
  tags: true
  author: κeen
  DateForm: "2006-01-02"
  SubTitle: Lispエイリアンの狂想曲